### ISSUE TITLE
Are they the same metric?

### ISSUE THREAD

**Issue by KleinYuan** [farrell236/DeepPose#5]
I wonder is the left-invariant Riemannian metric you use here: https://github.com/farrell236/DeepPose/blob/master/tensorflow/se3_geodesic_loss.py#L47

The same as the `left_canonical_metric` used here? https://github.com/geomstats/applications/blob/master/se3_pose_estimation/train_se3_kingscollege.py#L115

**Comment by farrell236** [comment]
Yes, [SE3_GROUP](https://github.com/geomstats/applications/blob/50aefdf14de308fc3c132784ebba9d329e47b087/se3_pose_estimation/train_se3_kingscollege.py#L115) is an object of [SpecialEuclideanGroup](https://github.com/geomstats/geomstats/blob/6856ac5e3a433b1b60fffba5951397815c290722/geomstats/special_euclidean_group.py#L36), which inherits ```LieGroup```. ```left_canonical_metric``` instantiates the object [InvariantMetric](https://github.com/geomstats/geomstats/blob/6856ac5e3a433b1b60fffba5951397815c290722/geomstats/lie_group.py#L40) in that class.

**Comment by KleinYuan** [comment]
Thanks for the clarification! @farrell236
